site_name: Elegant Git
site_url:
site_description:
site_author: Dmytro Serdiuk
repo_url: https://github.com/bees-hive/elegant-git
theme: readthedocs
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Configuration: configuration.md
  - Commands: commands.md
  - Release notes: https://github.com/bees-hive/elegant-git/releases
  - License: licence.md

copyright: Copyright &copy; 2019 <a href="https://extsoft.pro">Dmytro Serdiuk</a>, Maintained by <a href="https://github.com/bees-hive/elegant-git/graphs/contributors">project contributors</a>.
plugins:
    - search
